### ISSUE TITLE
failure if not submitting subnet IDs

### ISSUE THREAD

**Issue by smiller171** [LeafSoftware/python-lambder#5]
after adding VPC support, I can not create a non-VPC lambder:

```
lambder functions new --name emr-start --bucket com-openwhere-surge-lambda --timeout 30 --memory 128 --description "Start Surge EMR Cluster"
cd lambder-emr-start
lambder functions deploy
```

```
Traceback (most recent call last):
  File "/usr/local/bin/lambder", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 1057, in invoke
    Command.invoke(self, ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/lambder/cli.py", line 84, in functions
    context.obj = FunctionConfig(config_file)
  File "/Library/Python/2.7/site-packages/lambder/cli.py", line 74, in __init__
    self.subnet_ids = config['subnet_ids']
KeyError: 'subnet_ids'
```

**Comment by chalfant** [comment]
damn. on it.

**Comment by chalfant** [comment]
I think I need to do some work on the configuration file code...

**Comment by smiller171** [comment]
Well you're quick on the draw, so there's that.

**Comment by smiller171** [comment]
Could you cut a release with this bugfix so I don't have to maintain different versions for my different Lambders?

**Comment by chalfant** [comment]
1.2.2 should contain this bugfix. Is that version not working for you?

**Comment by smiller171** [comment]
Ah, I didn't know to look for it in pypi because you didn't cut the release in GitHub.
